kai2/urls.py
from django.urls import path

from . import views

app_name = 'kai2'
urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='index'),
    path('api/cities/', views.cityListJson, name='city_json'),
    path('api/post-schedule/', views.scheduleListJson, name='post_schedule'),
    path('api/bk/<int:id>/passenger/', views.passengerPostView, name='passenger'),
    path('api/bk/<int:id>/wl/', views.waitingListActionView, name='wl_confirm'),
    path('checkin/', views.checkinPostView, name='checkin'),
    path('checkin/<int:pk>/', views.TemplateDetailCheckin.as_view(), name='detail_checkin'),
    path('bookinglist/', views.BookedHistoryListView.as_view(), name='booked_history'),
    path('booking/<int:pk>/', views.TemplateBookingView.as_view(), name='booking'),
]

kai2/models.py
from django.db import models

from core.models import ComondBase

class Checkin(ComondBase):
    EKO = 'EKO'
    BIS = 'BIS'
    EKS = 'EKS'
    WAGONSELECT = (
        (EKO, 'Ekonomi'),
        (BIS, 'Bisnis'),
        (EKS, 'Eksekutif')
    ) 
    propscheduleid = models.CharField(max_length=10)
    orgcode = models.CharField(max_length=10)
    destcode = models.CharField(max_length=10)
    orgid = models.IntegerField()
    desid = models.IntegerField()
    noka = models.CharField(max_length=10)
    subclass = models.CharField(max_length=10)
    subclassid = models.IntegerField()
    wagonclasscode = models.CharField(max_length=10, choices=WAGONSELECT, default='EKO')
    wagonclassid = models.IntegerField()
    trainname = models.CharField(max_length=100)
    tripid = models.CharField(max_length=10)
    arrivaldatetime = models.DateTimeField()
    departdatetime = models.DateTimeField()
    stationnameorg = models.CharField(max_length=50)
    stationnamedest = models.CharField(max_length=50)
    amount = models.IntegerField()

    def __str__(self):
        return self.propscheduleid

class Booking(ComondBase):
    OPEN = 1
    WAITLIST = 2
    WAITPAYMENT = 3
    PAID = 4
    FINISH = 5
    DROP = 9
    STATESELECT = (
        (OPEN, 'Open Booking'),
        (WAITLIST, 'Waiting List'),
        (WAITPAYMENT, 'Waiting Payment'),
        (PAID, 'Paid'),
        (FINISH, 'Finish'),
        (DROP, 'Drop')
    )
    checkin = models.ForeignKey(Checkin, on_delete=models.PROTECT, related_name='checkin')
    status = models.PositiveSmallIntegerField(choices=STATESELECT, default=OPEN, editable=False)

    class Meta:
        ordering = [
            '-id'
        ]
    def __str__(self):
        return str(self.checkin)


class Passenger(ComondBase):
    booking = models.ForeignKey(Booking, on_delete=models.PROTECT, related_name='passengers', blank=True, null=True)
    passenger_nm = models.CharField(max_length=50)
    passenger_identity = models.CharField(max_length=30)


class Checkout(ComondBase):
    booking = models.ForeignKey(Booking, on_delete=models.PROTECT, related_name='checkout')
    paycode = models.CharField(max_length=20)
    net_amount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.paycode

kai2/forms.py
from django import forms

from .models import (
    Passenger,
)

# class KeretaSearchForm(forms.Form):
#     origin = forms.Field()
#     destination = forms.Field()
#     departdate = forms.DateField()


class PassengerForm(forms.ModelForm):
    class Meta:
        model = Passenger
        fields = [
            'passenger_nm',
            'passenger_identity',
        ]

kai2/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.generic import TemplateView, View, DetailView, ListView
from django.template.loader import render_to_string

from .utils import AESCipher
from .models import (
    Checkin, Booking,
)
from .forms import (
    PassengerForm,
)
from .tasks import (
    wl_process,
)

import requests, json



class HomeTemplateView(TemplateView):
    template_name = 'kai2/index.html'


def cityListJson(request):
    rson = []
    try:
        r = requests.get('https://booking.kai.id/api/stations2', timeout=10)
        if r.status_code == requests.codes.ok:
            rson = r.json()
    except :
        pass


    data = {
        'results': list(map(lambda x: dict(x, value=x['code']), rson))
    }
    
    return JsonResponse(data)


def scheduleListJson(request):
    data = dict()
    url = 'http://midsvc-rtsng.kai.id:8111'
    key = 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIkMnkkMTAkVVNNQ2pvdUlEV2lNWU9sMFFvemIxT3plbi51N2F1cHlUdTlIYnREcVJ1Zmg2Qlo1VlVnYlN8YW5kZXJpLnNldGlhd2FuQGdtYWlsLmNvbXwwODIyMTY0MTg0NTV8MTE0NDg3OCIsImV4cCI6MTU3MzgzMjc5NywiaXNzIjoiaHR0cHM6Ly9rYWlhY2Nlc3MxMS5rYWkuaWQvYXBpL3YxMi9hdXRoL2xvZ2luIn0.G847ZqfYfgx8CahArNdLP1LgkZsQS1n66sohSW1VbOUUxM7i2uRah1NREpce4PgGbrMjrbOV8YFG-eHk10lJnw'
    org = request.POST.get('org')
    dst = request.POST.get('dst')
    depart = request.POST.get('depart')
    y,m,d = depart.split('-')

    cipher = AESCipher('telo_pendem_tele')
    payload = {
        "staorigincode": cipher.encrypt(org),
        "stadestinationcode": cipher.encrypt(dst),
        "tripdate": cipher.encrypt(y+'-'+m.zfill(2)+'-'+d.zfill(2)),
    }
    content = {'origin': org, 'destination': dst, 'dep':depart, 'payloads': []}
    try :
        r = requests.post(
            url = url + '/rtsngmid/mobile/getscheduleune',
            data = json.dumps(payload),
            headers = {'Content-Type': 'application/json'},
            timeout=15
        )
        
        if r.status_code == requests.codes.ok:
            rson = r.json()
            content['payloads'] = list(map(lambda x: dict(x, amount=x['fares'][0]['amount']), rson['payload']))
            # print(rson['payload'])
    except :
        pass

    data['html'] = render_to_string(
        'kai2/include/kai-schedule-list.html',
        content, request=request
    )

    return JsonResponse(data)

def checkinPostView(request):
    if request.method == 'POST':
        propscheduleid=request.POST.get('propscheduleid')
        orgcode=request.POST.get('orgcode')
        orgid=request.POST.get('orgid')
        destcode=request.POST.get('destcode')
        desid=request.POST.get('desid')
        noka=request.POST.get('noka')
        subclass=request.POST.get('subclass')
        subclassid=request.POST.get('subclassid')
        wagonclasscode=request.POST.get('wagonclasscode')
        wagonclassid=request.POST.get('wagonclassid')
        trainname=request.POST.get('trainname')
        tripid=request.POST.get('tripid')
        arrivaldatetime=request.POST.get('arrivaldatetime')
        departdatetime=request.POST.get('departdatetime')
        stationnameorg=request.POST.get('stationnameorg')
        stationnamedest=request.POST.get('stationnamedest')
        amount=request.POST.get('amount')
    
        obj = Checkin.objects.create(
            propscheduleid=propscheduleid, orgcode=orgcode,
            orgid=orgid, destcode=destcode, desid=desid,
            noka=noka, subclass=subclass, subclassid=subclassid, wagonclasscode=wagonclasscode, wagonclassid=wagonclassid,
            trainname=trainname, tripid=tripid, arrivaldatetime=arrivaldatetime, departdatetime=departdatetime,
            stationnameorg=stationnameorg, stationnamedest=stationnamedest, amount=amount
        )
        booking_obj = Booking.objects.create(
            checkin=obj,
        )
        return redirect('kai2:booking', booking_obj.id)

    
class TemplateDetailCheckin(DetailView):
    template_name = 'kai2/checkin.html'
    model = Checkin


class TemplateBookingView(DetailView):
    template_name = 'kai2/booking.html'
    model = Booking
    # queryset = Booking.objects.filter(status=Booking.OPEN)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = PassengerForm()
        return context

def passengerPostView(request, id): # booking id
    data = dict()
    form = PassengerForm(request.POST or None)
    book_obj = get_object_or_404(Booking, pk=id)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.booking = book_obj
            instance.save()
            data['form_is_valid'] = True

        else :
            data['form_is_valid'] = False

    content = {
        'form': form,
        'object': book_obj,
    }
    data['html'] = render_to_string(
        'kai2/include/passenger-form.html', content, request=request
    )
    return JsonResponse(data)


def waitingListActionView(request, id): # booking id
    booking_obj = get_object_or_404(Booking, pk=id, status=Booking.OPEN)
    data = dict()
    data['form_is_valid'] = False
    if request.method == 'POST':
        booking_obj.status = Booking.WAITLIST
        booking_obj.save()
        data['form_is_valid'] = True

        wl_process(booking_obj.id, verbose_name='wl-{}'.format(booking_obj.id), creator=booking_obj, repeat=30, repeat_until=booking_obj.checkin.departdatetime)

    data['html'] = render_to_string(
        'kai2/include/wl-action.html', {'object': booking_obj}, request=request
    )
    return JsonResponse(data)


class BookedHistoryListView(ListView):
    template_name = 'kai2/booking-list-history.html'
    model = Booking

templates/kai2/base.html
{% extends 'base.html' %}

{% block sub_base %}

    {% block content %}
    {% endblock %}
{% endblock %}

templates/kai2/booking-list-history.html
{% extends 'kai2/base.html' %}

{% block content %}
<div class="ui vertical segment">
    <div class="ui container">
        <div class="ui text menu">
            <div class="item header">
                Booking History
            </div>
        </div>
        <table class="ui striped table">
            <tbody>
                {% for obj in object_list %}
                <tr onclick="window.location.href='{% url 'kai2:booking' obj.id %}'">
                    <td>
                        <h3 class="ui orange center aligned header" style="display: inline-block">
                            {{ obj.checkin.orgcode}}
                            <div class="sub header">
                                {{ obj.checkin.stationnameorg }}
                            </div>
                        </h3>
                        <!-- <h5 class="ui center aligned header" style="display: inline-block"> -->
                            <i class="right arrow icon"></i>
                        <!-- </h5> -->
                        <h3 class="ui orange center aligned header" style="display: inline-block">
                            {{ obj.checkin.destcode }}
                            <div class="sub header">
                                {{ obj.checkin.stationnamedest }}
                            </div>
                        </h3>
                    </td>
                    <td>
                        <div class="ui sub header">
                            <div class="content">KA. {{ obj.checkin.trainname }} ({{ obj.checkin.noka }})</div>
                        </div>
                        <span><i class="train icon"></i>{{ obj.checkin.get_wagonclasscode_display }} - Subclass {{ obj.checkin.subclass }}</span>
                    </td>
                    <td>
                        <div class="ui sub header">
                            Tanggal Berangkat
                        </div>
                        <span>{{ obj.checkin.departdatetime|date:"Y-m-d" }}</span> &nbsp;
                        <span><i class="clock outline icon"></i>{{ obj.checkin.departdatetime|date:"H:i"}}</span>
                    </td>
                    <td>
                        <a href="#" class="ui right ribbon label">
                            {{ obj.get_status_display }}
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/kai2/booking.html
{% extends 'kai2/base.html' %}

{% block content %}
<div class="ui vertical segment">
    <div class="ui container">
        <div class="ui stackable equal width grid">
            <div class="row">
                <div class="column">
                    <h3 class="ui header">
                        <i class="train icon"></i>
                        <div class="content">
                            KA. {{ object.checkin.trainname }} ({{ object.checkin.noka }})
                        <div class="sub header">
                            {{ object.checkin.get_wagonclasscode_display }} - Subclass {{ object.checkin.subclass }}
                        </div>
                        </div>
                    </h3>
                </div>
            </div>
            <div class="row">
                <div class="column">
                    <h3 class="ui orange left floated header">
                        {{ object.checkin.orgcode }}
                        <div class="sub header">{{ object.checkin.stationnameorg }}</div>
                    </h3>
                    <h4 class="ui left floated header">
                        <i class="right arrow icon"></i>
                    </h4>
                    <h3 class="ui orange left floated header">
                        {{ object.checkin.destcode }}
                        <div class="sub header">{{ object.checkin.stationnamedest }}</div>
                    </h3>
                </div>
                <div class="column">
                    <div class="ui sub header">
                        Tanggal Berangkat
                    </div>
                    <span>{{ object.checkin.departdatetime|date:"Y-m-d" }}</span>
                    <div class="ui sub header">
                        Jam Berangkat
                    </div>
                    <span><i class="clock outline icon"></i>{{ object.checkin.departdatetime|date:"H:i" }}</span>
                </div>
                <div class="column">
                    <div class="ui sub header">
                        Tanggal Tiba
                    </div>
                    <span>{{ object.checkin.arrivaldatetime|date:"Y-m-d" }}</span>
                    <div class="ui sub header">
                        Jam Tiba
                    </div>
                    <span><i class="clock outline icon"></i>{{ object.checkin.arrivaldatetime|date:"H:i" }}</span>
                </div>
            </div>
            <div class="row">
                <div class="column" id="passenger-id">
                    <!-- Passenger Content -->
                    {% include 'kai2/include/passenger-form.html' %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script>
    $(document).ready(function() {
        $('#passenger-id').on('click', '.js-wl-button', function() {
            var btn = $(this);
            $.ajax({
                url: btn.attr('data-url'),
                dataType: 'json',
                beforeSend: function() {
                    var modal = $('#modal-id');
                    modal.addClass('small basic').modal('show');
                }, success: function(data) {
                    $('#modal-id').html(data.html);
                }
            });
            return false;
        });

        $('#modal-id').on('submit', '.wl-action-form', function() {
            var form = $(this);
            $.ajax({
                url: form.attr('action'),
                type: form.attr('method'),
                dataType: 'json',
                data: form.serialize(),
                success: function(data) {
                    if(data.form_is_valid) {
                        $('#modal-id').modal('hide');
                    }
                }
            });
            return false;
        });

        $('#passenger-id').on('submit', '.js-passenger-form', function() {
            var form = $(this);
            $.ajax({
                url: form.attr('action'),
                type: form.attr('method'),
                dataType: 'json',
                data: form.serialize(),
                success: function(data) {
                    if(data.form_is_valid) {
                        $('#passenger-id').html(data.html);
                    }
                }
            });
            return false;
        });
    });
</script>
{% endblock %}

templates/kai2/checkin.html
{% extends 'kai2/base.html' %}

{% block content %}
<div class="ui vertical segment">
    <div class="ui container">
        <div class="ui stackable equal width grid">
            <div class="row">
                <div class="column">
                    <h3 class="ui header">
                        <i class="train icon"></i>
                        <div class="content">
                            KA. {{ object.trainname }} ({{ object.noka }})
                        <div class="sub header">
                            {{ object.get_wagonclasscode_display }} - Subclass {{ data.suclass }}
                        </div>
                        </div>
                    </h3>
                </div>
            </div>
            <div class="row">
                <div class="column">
                    <h3 class="ui orange left floated header">
                        {{ object.orgcode }}
                        <div class="sub header">{{ object.stationnameorg }}</div>
                    </h3>
                    <h4 class="ui left floated header">
                        <i class="right arrow icon"></i>
                    </h4>
                    <h3 class="ui orange left floated header">
                        {{ object.destcode }}
                        <div class="sub header">{{ object.stationnamedest }}</div>
                    </h3>
                </div>
                <div class="column">
                    <div class="ui sub header">
                        Tanggal Berangkat
                    </div>
                    <span>{{ object.departdatetime|date:"Y-m-d" }}</span>
                    <div class="ui sub header">
                        Jam Berangkat
                    </div>
                    <span><i class="clock outline icon"></i>{{ object.departdatetime|date:"H:i" }}</span>
                </div>
                <div class="column">
                    <div class="ui sub header">
                        Tanggal Tiba
                    </div>
                    <span>{{ object.arrivaldatetime|date:"Y-m-d" }}</span>
                    <div class="ui sub header">
                        Jam Tiba
                    </div>
                    <span><i class="clock outline icon"></i>{{ object.arrivaldatetime|date:"H:i" }}</span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/kai2/index.html
{% extends 'kai2/base.html' %}

{% block content %}
<div class="ui vertical segment">
    <div class="ui container">
        <div class="ui segment">
            <form action="{% url 'kai2:post_schedule' %}" method="post" class="ui form search-form-js">
                {% csrf_token %}
                <div class="fields equal width">
                    <div class="field">
                        <label for="">St. Keberangkatan</label>
                        <div class="ui search selection dropdown">
                            <input type="hidden" name="org">
                            <i class="dropdown icon"></i>
                            <div class="default text">Origin City</div>
                            <div class="menu"></div>
                        </div>
                    </div>
                    <div class="field">
                        <label for="">St. Tujuan</label>
                        <div class="ui search selection dropdown">
                            <input type="hidden" name="dst">
                            {{ form.destination }}
                            <i class="dropdown icon"></i>
                            <div class="default text">Destination City</div>
                            <div class="menu"></div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label for="">Tanggal Berangkat</label>
                    <div class="ui calendar" id="depart-date">
                        <div class="ui input left icon">
                            <i class="calendar icon"></i>
                            <input type="text" placeholder="Date" name="depart">
                        </div>
                    </div>
                </div>
                <button type="submit" class="ui orange button"><i class="search icon"></i> Cari Perjalanan</button>
            </form>
        </div>
    </div>
</div>
<div class="ui vertical segment">
    <div class="ui container" id="content-id">
        <!-- content -->
    </div>
</div>

{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
    $('.ui.dropdown').dropdown({
        apiSettings: {
            url: "{% url 'kai2:city_json' %}"
        },
        filterRemoteData: true
    });

    $('#depart-date')
        .calendar({
            monthFirst: false,
            type: 'date',
            formatter: {
            date: function (date, settings) {
                if (!date) return '';
                var day = date.getDate();
                var month = date.getMonth() + 1;
                var year = date.getFullYear();
                return year + '-' + month + '-' + day;
            }
            }
        });


    $('.search-form-js').on('submit', function() {
        var form = $(this);
        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'json',
            data: form.serialize(),
            success: function(data) {
                $('#content-id').html(data.html);
            }
        })
        return false;
    });
});
</script>
{% endblock %}