kai2/urls.py
from django.urls import path

from . import views

app_name = 'kai2'
urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='index'),
    path('api/cities/', views.cityListJson, name='city_json'),
    path('api/post-schedule/', views.scheduleListJson, name='post_schedule'),
    path('api/bk/<int:id>/passenger/', views.passengerPostView, name='passenger'),
    path('api/bk/<int:id>/wl/', views.waitingListActionView, name='wl_confirm'),
    path('checkin/', views.checkinPostView, name='checkin'),
    path('checkin/<int:pk>/', views.TemplateDetailCheckin.as_view(), name='detail_checkin'),
    path('bookinglist/', views.BookedHistoryListView.as_view(), name='booked_history'),
    path('booking/<int:pk>/', views.TemplateBookingView.as_view(), name='booking'),
]

kai2/models.py
from django.db import models

from core.models import ComondBase

class Checkin(ComondBase):
    EKO = 'EKO'
    BIS = 'BIS'
    EKS = 'EKS'
    WAGONSELECT = (
        (EKO, 'Ekonomi'),
        (BIS, 'Bisnis'),
        (EKS, 'Eksekutif')
    ) 
    propscheduleid = models.CharField(max_length=10)
    orgcode = models.CharField(max_length=10)
    destcode = models.CharField(max_length=10)
    orgid = models.IntegerField()
    desid = models.IntegerField()
    noka = models.CharField(max_length=10)
    subclass = models.CharField(max_length=10)
    subclassid = models.IntegerField()
    wagonclasscode = models.CharField(max_length=10, choices=WAGONSELECT, default='EKO')
    wagonclassid = models.IntegerField()
    trainname = models.CharField(max_length=100)
    tripid = models.CharField(max_length=10)
    arrivaldatetime = models.DateTimeField()
    departdatetime = models.DateTimeField()
    stationnameorg = models.CharField(max_length=50)
    stationnamedest = models.CharField(max_length=50)
    amount = models.IntegerField()

    def __str__(self):
        return self.propscheduleid

class Booking(ComondBase):
    OPEN = 1
    WAITLIST = 2
    WAITPAYMENT = 3
    PAID = 4
    FINISH = 5
    DROP = 9
    STATESELECT = (
        (OPEN, 'Open Booking'),
        (WAITLIST, 'Waiting List'),
        (WAITPAYMENT, 'Waiting Payment'),
        (PAID, 'Paid'),
        (FINISH, 'Finish'),
        (DROP, 'Drop')
    )
    checkin = models.ForeignKey(Checkin, on_delete=models.PROTECT, related_name='checkin')
    status = models.PositiveSmallIntegerField(choices=STATESELECT, default=OPEN, editable=False)

    class Meta:
        ordering = [
            '-id'
        ]
    def __str__(self):
        return str(self.checkin)


class Passenger(ComondBase):
    booking = models.ForeignKey(Booking, on_delete=models.PROTECT, related_name='passengers', blank=True, null=True)
    passenger_nm = models.CharField(max_length=50)
    passenger_identity = models.CharField(max_length=30)


class Checkout(ComondBase):
    booking = models.ForeignKey(Booking, on_delete=models.PROTECT, related_name='checkout')
    paycode = models.CharField(max_length=20)
    net_amount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.paycode

kai2/forms.py
from django import forms

from .models import (
    Passenger,
)

# class KeretaSearchForm(forms.Form):
#     origin = forms.Field()
#     destination = forms.Field()
#     departdate = forms.DateField()


class PassengerForm(forms.ModelForm):
    class Meta:
        model = Passenger
        fields = [
            'passenger_nm',
            'passenger_identity',
        ]

kai2/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views.generic import TemplateView, View, DetailView, ListView
from django.template.loader import render_to_string

from .utils import AESCipher
from .models import (
    Checkin, Booking,
)
from .forms import (
    PassengerForm,
)
from .tasks import (
    wl_process,
)

import requests, json



class HomeTemplateView(TemplateView):
    template_name = 'kai2/index.html'


def cityListJson(request):
    rson = []
    try:
        r = requests.get('https://booking.kai.id/api/stations2', timeout=10)
        if r.status_code == requests.codes.ok:
            rson = r.json()
    except :
        pass


    data = {
        'results': list(map(lambda x: dict(x, value=x['code']), rson))
    }
    
    return JsonResponse(data)


def scheduleListJson(request):
    data = dict()
    url = 'http://midsvc-rtsng.kai.id:8111'
    key = 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIkMnkkMTAkVVNNQ2pvdUlEV2lNWU9sMFFvemIxT3plbi51N2F1cHlUdTlIYnREcVJ1Zmg2Qlo1VlVnYlN8YW5kZXJpLnNldGlhd2FuQGdtYWlsLmNvbXwwODIyMTY0MTg0NTV8MTE0NDg3OCIsImV4cCI6MTU3MzgzMjc5NywiaXNzIjoiaHR0cHM6Ly9rYWlhY2Nlc3MxMS5rYWkuaWQvYXBpL3YxMi9hdXRoL2xvZ2luIn0.G847ZqfYfgx8CahArNdLP1LgkZsQS1n66sohSW1VbOUUxM7i2uRah1NREpce4PgGbrMjrbOV8YFG-eHk10lJnw'
    org = request.POST.get('org')
    dst = request.POST.get('dst')
    depart = request.POST.get('depart')
    y,m,d = depart.split('-')

    cipher = AESCipher('telo_pendem_tele')
    payload = {
        "staorigincode": cipher.encrypt(org),
        "stadestinationcode": cipher.encrypt(dst),
        "tripdate": cipher.encrypt(y+'-'+m.zfill(2)+'-'+d.zfill(2)),
    }
    content = {'origin': org, 'destination': dst, 'dep':depart, 'payloads': []}
    try :
        r = requests.post(
            url = url + '/rtsngmid/mobile/getscheduleune',
            data = json.dumps(payload),
            headers = {'Content-Type': 'application/json'},
            timeout=15
        )
        
        if r.status_code == requests.codes.ok:
            rson = r.json()
            content['payloads'] = list(map(lambda x: dict(x, amount=x['fares'][0]['amount']), rson['payload']))
            # print(rson['payload'])
    except :
        pass

    data['html'] = render_to_string(
        'kai2/include/kai-schedule-list.html',
        content, request=request
    )

    return JsonResponse(data)

def checkinPostView(request):
    if request.method == 'POST':
        propscheduleid=request.POST.get('propscheduleid')
        orgcode=request.POST.get('orgcode')
        orgid=request.POST.get('orgid')
        destcode=request.POST.get('destcode')
        desid=request.POST.get('desid')
        noka=request.POST.get('noka')
        subclass=request.POST.get('subclass')
        subclassid=request.POST.get('subclassid')
        wagonclasscode=request.POST.get('wagonclasscode')
        wagonclassid=request.POST.get('wagonclassid')
        trainname=request.POST.get('trainname')
        tripid=request.POST.get('tripid')
        arrivaldatetime=request.POST.get('arrivaldatetime')
        departdatetime=request.POST.get('departdatetime')
        stationnameorg=request.POST.get('stationnameorg')
        stationnamedest=request.POST.get('stationnamedest')
        amount=request.POST.get('amount')
    
        obj = Checkin.objects.create(
            propscheduleid=propscheduleid, orgcode=orgcode,
            orgid=orgid, destcode=destcode, desid=desid,
            noka=noka, subclass=subclass, subclassid=subclassid, wagonclasscode=wagonclasscode, wagonclassid=wagonclassid,
            trainname=trainname, tripid=tripid, arrivaldatetime=arrivaldatetime, departdatetime=departdatetime,
            stationnameorg=stationnameorg, stationnamedest=stationnamedest, amount=amount
        )
        booking_obj = Booking.objects.create(
            checkin=obj,
        )
        return redirect('kai2:booking', booking_obj.id)

    
class TemplateDetailCheckin(DetailView):
    template_name = 'kai2/checkin.html'
    model = Checkin


class TemplateBookingView(DetailView):
    template_name = 'kai2/booking.html'
    model = Booking
    # queryset = Booking.objects.filter(status=Booking.OPEN)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = PassengerForm()
        return context

def passengerPostView(request, id): # booking id
    data = dict()
    form = PassengerForm(request.POST or None)
    book_obj = get_object_or_404(Booking, pk=id)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit=False)
            instance.booking = book_obj
            instance.save()
            data['form_is_valid'] = True

        else :
            data['form_is_valid'] = False

    content = {
        'form': form,
        'object': book_obj,
    }
    data['html'] = render_to_string(
        'kai2/include/passenger-form.html', content, request=request
    )
    return JsonResponse(data)


def waitingListActionView(request, id): # booking id
    booking_obj = get_object_or_404(Booking, pk=id, status=Booking.OPEN)
    data = dict()
    data['form_is_valid'] = False
    if request.method == 'POST':
        booking_obj.status = Booking.WAITLIST
        booking_obj.save()
        data['form_is_valid'] = True

        wl_process(booking_obj.id, verbose_name='wl-{}'.format(booking_obj.id), creator=booking_obj, repeat=30, repeat_until=booking_obj.checkin.departdatetime)

    data['html'] = render_to_string(
        'kai2/include/wl-action.html', {'object': booking_obj}, request=request
    )
    return JsonResponse(data)


class BookedHistoryListView(ListView):
    template_name = 'kai2/booking-list-history.html'
    model = Booking

templates/kai2/include/kai-schedule-list.html
{% load humanize %}
<div class="ui stackable grid">
    <div class="row">
        <div class="column">
            <div class="ui text huge menu">
                <div class="item">
                    <i class="train icon"></i> {{ origin }} - {{ destination }}
                </div>
                <div class="item">
                    <i class="calendar icon"></i> {{ dep }}
                </div>
            </div>
            <table class="ui table">
                <tbody>
                    {% for i in payloads %}
                    <tr>
                        <td>
                            <div class="ui sub header">{{ i.trainname }} ({{ i.noka }})</div>
                            <span class="">{{ i.wagonclasscode }}</span>
                        </td>
                        <td>
                            <div class="ui sub header">{{ i.stationnameorg }}</div>
                            <span><i class="clock outline icon"></i> {{ i.departuretime }}</span>
                        </td>
                        <td>
                            <div class="ui sub header">{{ i.stationnamedest }}</div>
                            <span><i class="clock outline icon"></i> {{ i.arrivaltime }}</span>
                        </td>
                        <td>
                            <div class="ui orange huge sub header">
                                IDR {{ i.amount|intcomma }}
                            </div>
                            <!-- <span><i class="chair icon"></i> {{ i.availability }} kursi</span> -->
                        </td>
                        <td class="right aligned">
                            <form id="wr-{{ forloop.counter }}" action="{% url 'kai2:checkin' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="propscheduleid" value="{{i.propscheduleid}}">
                                <input type="hidden" name="orgcode" value="{{i.orgcode}}">
                                <input type="hidden" name="orgid" value="{{i.orgid}}">
                                <input type="hidden" name="destcode" value="{{i.destcode}}">
                                <input type="hidden" name="desid" value="{{i.desid}}">
                                <input type="hidden" name="noka" value="{{i.noka}}">
                                <input type="hidden" name="subclass" value="{{i.subclass}}">
                                <input type="hidden" name="subclassid" value="{{i.subclassid}}">
                                <input type="hidden" name="wagonclasscode" value="{{i.wagonclasscode}}">
                                <input type="hidden" name="wagonclassid" value="{{i.wagonclassid}}">
                                <input type="hidden" name="trainname" value="{{i.trainname}}">
                                <input type="hidden" name="tripid" value="{{i.tripid}}">
                                <input type="hidden" name="arrivaldatetime" value="{{i.arrivaldatetime}}">
                                <input type="hidden" name="departdatetime" value="{{i.departdatetime}}">
                                <input type="hidden" name="stationnameorg" value="{{i.stationnameorg}}">
                                <input type="hidden" name="stationnamedest" value="{{i.stationnamedest}}">
                                <input type="hidden" name="amount" value="{{i.amount}}">
                            </form>
                            {% if i.availability > 0%}
                            <button type="submit" form="wr-{{ forloop.counter }}" class="ui tiny teal button wl-button-js">
                                Booking
                            </button>
                            <br>
                                {% if i.availability > 50 %}
                                <small>Tersedia</small>
                                {% else %}
                                <small>{{ i.availability }} kursi</small>
                                {% endif %}
                            {% else %}
                            <button type="submit" form="wr-{{ forloop.counter }}" class="ui tiny orange button wl-button-js">
                                Waiting List
                            </button>
                            <br>
                            <small>Habis</small>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

templates/kai2/include/passenger-form.html
<div class="ui text menu">
    <div class="item header"><i class="user icon"></i> Data Penumpang</div>
</div>
{% if object.passengers.count == 0 %}
<div class="ui segment">
    <form action="{% url 'kai2:passenger' object.id  %}" method="post" class="ui form js-passenger-form">
        {% csrf_token %}
        <div class="equal width fields">
            <div class="field">
                <label for="">Nama</label>
                {{ form.passenger_nm }}
            </div>
            <div class="field">
                <label for="">No. Identitas</label>
                {{ form.passenger_identity }}
            </div>
        </div>
        <div class="field">
            <button type="submit" class="ui orange button">Lanjutkan</button>
        </div>
    </form>
</div>
{% else %}
    <table class="ui table">
        <tbody>
        {% for p in object.passengers.all %}
            <tr>
                <td>
                    <div class="ui sub header">
                        Penumpang {{ forloop.counter }}
                    </div>
                    <span>{{ p.passenger_nm }}</span>
                </td>
                <td>
                    <div class="ui sub header">
                        No. Identitas
                    </div>
                    <span>{{ p.passenger_identity }}</span>
                </td>
            </tr>                       
        {% endfor %}
        </tbody>
    </table>
    {% if object.status == 1 %}
    <button class="ui orange button js-wl-button" type="button" data-url="{% url 'kai2:wl_confirm' object.id %}">Lanjutkan</button>
    {% endif %}
{% endif %}

templates/kai2/include/wl-action.html
<div class="ui icon header">
    Booking Confirmation
</div>
<div class="content center aligned">
    <form id="wlform-id" action="{% url 'kai2:wl_confirm' object.id %}" method="post" class="ui form wl-action-form">
        {% csrf_token %}
        <div class="field center aligned">
            <p>
                Proses booking waiting list memakan waktu sampai tiket didapat. Apakah Anda yakin melanjutkan?
            </p>
        </div>
    </form>
</div>
<div class="actions">
    <button type="button" class="ui red basic cancel inverted button">
        <i class="remove icon"></i>
        Tidak
    </button>
    <button type="submit" form="wlform-id" class="ui green ok inverted button">
        <i class="checkmark icon"></i>
        Iya Lanjutkan
    </button>
</div>